### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jack793**
Update markdown links README.md

### CODE REVIEW

**Comment by thinline72** [comment]
Hi @jack793 ,

Thanks for you pull-request. Could you provide a bit more info why these changes are needed, please?

**Comment by thinline72** [comment]
BTW, I'm working on updating this repo with some examples on how to use DL-based models (in PyTorch) as well as appropriate docker files for each solution. Hopefully I'll finish in the next few weeks.

**Comment by jack793** [comment]
hi thanks for your answer :D is only a stupid change for make working the links in toc again because when you click it now nothing appens

On 18 Oct 2019, at 13:36, Sava Kalbachou <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jack793<https://github.com/jack793> ,

Thanks for you pull-request. Could you provide a bit more info why these changes are needed, please?

**Comment by thinline72** [comment]
Oh yes, indeed. Thanks! Just merged it.

**Pull request merged**
